### ISSUE TITLE
Config.custom.yml not writable !

### ISSUE THREAD

**Issue by seedboxer** [arvida42/davdebrid#3]
Thanks for this nice useful project im really glad you made it.

I tried alot of things i cant make the config.custom.yml writeable.

I tried alot of things i cant make the config.custom.yml writeable with mounted. I wanted to try a few small changes.

**Comment by seedboxer** [comment]
could we try

```
directories:

  - name: 'All'
    unique: false
    cond: {}

  - name: 'Shows'
    unique: true
    cond:
      or:
        regex: '[0-9]+E[0-9]+|[0-9]+x[0-9]+|[Ss][0-9]{2}|[Ee][0-9]{2}'
        minVideosInParent: 3
      fileTypes:
        - 'video'
        - 'subtitle'
      
  - name: 'Movies'
    unique: true
    cond:
      fileTypes:
        - 'video'
        - 'subtitle'
```
I tried so many things but cant get the config.custom.yml to be writeable
